name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push vote image
        uses: docker/build-push-action@v5
        with:
          context: ./vote
          push: true
          tags: sandeep2862/voting-app-vote:latest

      - name: Build and push result image
        uses: docker/build-push-action@v5
        with:
          context: ./result
          push: true
          tags: sandeep2862/voting-app-result:latest

      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: sandeep2862/voting-app-worker:latest
